# Generated by Django 3.2.7 on 2021-09-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.ManyToManyField(related_name='categoria', to='core.Tipo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tipo',
            field=models.ManyToManyField(related_name='fornecedor', to='core.Tipo'),
        ),
    ]
