# Generated by Django 3.2.7 on 2021-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210925_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereco'),
        ),
    ]
