# Generated by Django 3.2.7 on 2021-09-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210925_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ManyToManyField(related_name='tipo', to='core.Categoria'),
        ),
    ]
